# Generated by Django 5.0 on 2024-04-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='media/restaurant_images/'),
        ),
    ]
