# Generated by Django 5.0 on 2024-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0004_restaurantimage_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='rating',
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
