# Generated by Django 5.0 on 2024-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0006_alter_restaurantreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='priceRange',
            field=models.IntegerField(default=0),
        ),
    ]
