# Generated by Django 5.0 on 2024-04-13 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0009_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100000)),
                ('mapLocation', models.TextField(max_length=100000)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('description', models.TextField(max_length=1000000)),
                ('priceRange', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='TourApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation_images/')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_images', to='TourApp.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(max_length=1000000)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_reviews', to='TourApp.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
